server:
  port: 8080
management:
  security:
    enabled: false #关掉安全认证
  port: 8088 #管理端口调整成8088
  context-path: /monitor #actuator的访问路径
endpoints:
  shutdown:
    enabled: true

info:
   app:
      name: "@project.name@" #从pom.xml中获取
      description: "@project.description@"
      version: "@project.version@"
      spring-boot-version: "@project.parent.version@"
